### ISSUE TITLE
Npm not working

### ISSUE THREAD

**Issue by saurabh0227** [VuongVu/word2pdf#2]
Even after updating to the latest version, the API is not working.

**Comment by cristicismas** [comment]
Not working for me either. When word2pdf requests the pdf it gets an html file instead.

**Comment by VuongVu** [comment]
I think the author of the server converter has changed the way to send data. Now, I don't have too much time to maintain and update the library bc I busy with my business.

Sorry for that, if you or others have any update, please make a PR or fork my repo and update it for the community. 

Thank you.

**Comment by pointnet** [comment]
I have the fix, working on a PR!

**Comment by VuongVu** [comment]
You can make a PR and I will merge and publish on npmjs.

**Comment by pointnet** [comment]
done => https://github.com/VuongVu/word2pdf/pull/3

**Comment by pointnet** [comment]
I didn't updated the package version, i'll let you do when publishing

**Comment by VuongVu** [comment]
@pointnet thank you so much. I updated & published to npmjs.

**Comment by cristicismas** [comment]
Still doesn't seem to work for me. I'm getting this error now:

```
TypeError: Cannot read property 'name' of undefined
at FormData._getContentDisposition (/home/cristi/projects/resume-architect/server/node_modules/form-data/lib/form_data.js:226:40)
at FormData._multiPartHeader (/home/cristi/projects/resume-architect/server/node_modules/form-data/lib/form_data.js:177:33)
at FormData.append (/home/cristi/projects/resume-architect/server/node_modules/form-data/lib/form_data.js:70:21)
at data (/home/cristi/projects/resume-architect/server/node_modules/word2pdf/index.js:53:10)
at new Promise (<anonymous>)
at Object.word2pdf [as default] (/home/cristi/projects/resume-architect/server/node_modules/word2pdf/index.js:34:22)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
This line seems to be the culprit: 
`form.append("__VIEWSTATE", hiddens.__VIEWSTATE);`

**Comment by VuongVu** [comment]
I checked in local and its work. 
You can use my example and notice the file path.

**Comment by pointnet** [comment]
fixed by https://github.com/VuongVu/word2pdf/pull/4

**Comment by cristicismas** [comment]
If i use the code in #4 everything works. Thank you.

If you could update the npm package again I would be grateful.

**Comment by VuongVu** [comment]
@cristicismas check the new version

**Comment by cristicismas** [comment]
That's great, thanks!

**Comment by cristicismas** [comment]
Now I'm getting back html with an 'Internal Server Error' message. I suspect it's from their end since the html is basically their website, but I may be wrong. 

This is what the html looks like:
![Screenshot_2020-04-05 Internal server error](https://user-images.githubusercontent.com/31389099/78503481-74085600-776f-11ea-886b-f83ae4ca0e86.png)

I don't understand why the code from #4 worked before but it doesn't work now. Sorry to keep bringing this up. I don't think it's from my end, but again, I may be wrong.

**Comment by pointnet** [comment]
They've just added a cookie protection stuff, i'm working on it right now

**Comment by pointnet** [comment]
Please check https://github.com/VuongVu/word2pdf/pull/5 for cookie stuff

**Comment by cristicismas** [comment]
_"Please, use our website directly <a href='https://convertonlinefree.com/WordToPDF.aspx' target='_blank'>https://convertonlinefree.com/WordToPDF.aspx</a>"_

This is what I'm getting back :( I guess they don't want to support scrapers anymore.

**Comment by pointnet** [comment]
same here... let me check how to solve it

**Comment by cristicismas** [comment]
I suppose you could change the user agent to fake being and actual user?

**Comment by pointnet** [comment]
cookie is now encoded... and it's not base64

**Comment by pointnet** [comment]
fixed in https://github.com/VuongVu/word2pdf/pull/7

**Comment by cristicismas** [comment]
#7 Works great, thank you.

**Comment by lukasreinhard** [comment]
when i testing #7 and result is error "Internal server error". But yesterday is fine.
![Screen Shot 2020-04-06 at 13 03 25](https://user-images.githubusercontent.com/53042611/78527437-0b6cb800-7807-11ea-9054-947e393dbc06.png)

**Comment by pointnet** [comment]
The website is crashing also on Word to PDF, we need to wait for them to fix their issue.
Script in the package is working, you can try with https://convertonlinefree.com/ImageToPDFEN.aspx to check that everything is fine on our side.

**Comment by lukasreinhard** [comment]
I use this url https://convertonlinefree.com/ImageToPDFEN.aspx and i got
the same error.

Pada tanggal Sen, 6 Apr 2020 13.46, pointnet <notifications@github.com>
menulis:

**Comment by pointnet** [comment]
There's a bit of code to change to use the ImageToPDF stuff but it works well.
See on their website, you can convert an image but not a word document.

**Comment by lukasreinhard** [comment]
Oh i see, but i need to convert docx to pdf. When the final update so the
docx can be converted bro? Thanks

Pada tanggal Sen, 6 Apr 2020 14.25, pointnet <notifications@github.com>
menulis:

**Comment by pointnet** [comment]
There's nothing to change in this package, we just have to wait that convertonlinefree fix his issues regarding word to pdf

**Comment by lukasreinhard** [comment]
thanks bro for your infomation.

**Comment by vaishali-bluepineapple** [comment]
https://convertonlinefree.com/ is working for doc and docx now. But this npm is still not working. Please check.

**Comment by Ramprasathb** [comment]
My observation : 
This works if we make the request from local, but not when it is made from a server

**Comment by cristicismas** [comment]
I'm getting back this html now:
```html
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://convertonlinefree.com/WordToPDF.aspx">here</a>.</h2>
</body></html>
```

If I simply change the url to `https://convertonlinefree.com/WordToPDF.aspx` I'm getting back this:

```html
<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="https://convertonlinefree.com/">here</a></body>
```

**Comment by khaledhublo** [comment]
As an alternative I'd recommend this service (Which I'm maintaining):
https://www.npmjs.com/package/iva-converter
 something to know is that convertonlinefree.com and the creator of the package don't know each other. And I spoke to convertonlinefree.com they don't want him using this package.
